// Code generated by "stringer -type=Type"; DO NOT EDIT

package messages

import "fmt"

const _Type_name = "PingIdPongIdJoinIdJoinedIdStayIdLeaveIdGameStateIdMoveIdBuildIdRepairIdAttackIdOperateId"

var _Type_index = [...]uint8{0, 6, 12, 18, 26, 32, 39, 50, 56, 63, 71, 79, 88}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
