sudo: false # enable container-based infrastructure

addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      # packahe list:
      # https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
      - python3.5 python3.5-dev python3.5-venv libglew-dev


before_install:
  # get Go 1.8 and installs it as current Go version
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.8 bash)"
  - go version

install:
  - python3.5 bootstrap.py --git-http


script:
  # echo 'Client tests'
  - echo $GOPATH
  - export GOPATH=$PWD
  - cd src/server && go test ./...
