sudo: false

addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.5 python3.5-dev

script:
  - python3.5 bootstrap.py --no-venv --git-http
